#
# Makefile for the kernel block device drivers.
#
# 12 June 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

# for nand test
# obj-$(CONFIG_SUN6I_NANDFLASH_TEST) += nand/