obj-$(CONFIG_SND_SUN6I_SOC_PCM_INTERFACE) += sun6i-pcm.o
obj-$(CONFIG_SND_SUN6I_SOC_PCM_INTERFACE) += sun6i-pcmdma.o
obj-$(CONFIG_SND_SUN6I_SOC_PCM_INTERFACE) += sndpcm.o
obj-$(CONFIG_SND_SUN6I_SOC_PCM_INTERFACE) += sun6i-sndpcm.o
 
