
obj-$(CONFIG_SND_SUN6I_SOC_HDMIAUDIO) += sun6i-hdmiaudio.o
obj-$(CONFIG_SND_SUN6I_SOC_HDMIAUDIO) += sun6i-hdmipcm.o
obj-$(CONFIG_SND_SUN6I_SOC_HDMIAUDIO) += sndhdmi.o
obj-$(CONFIG_SND_SUN6I_SOC_HDMIAUDIO) += sun6i-sndhdmi.o
 
