obj-$(CONFIG_LYCHEE_LCD_SUN6I) += lcd.o

lcd-objs := dev_lcd.o lcd0_panel_cfg.o lcd1_panel_cfg.o lcd_bak/lcd_edp_anx9804.o lcd_bak/lcd_edp_anx6345.o lcd_bak/lcd_B079XAN01.o lcd_bak/lcd_vvx07h005a00.o
