

obj-$(CONFIG_SND_SUN6I_SOC_SPDIF) += sun6i_spdif.o
obj-$(CONFIG_SND_SUN6I_SOC_SPDIF) += sun6i_spdma.o
obj-$(CONFIG_SND_SUN6I_SOC_SPDIF) += sndspdif.o
obj-$(CONFIG_SND_SUN6I_SOC_SPDIF) += sun6i_sndspdif.o


